version: '3'

services:
  micro-service-s3:
    container_name: micro-service-s3
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./:/var/www/html/
      - ./apache_log/:/var/log/apache2/
      - ./apache_php_log/:/var/log/php/
    ports:
      - 8000:80
  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 8900:8900
    volumes:
      - minio:/data/minio
    command: 'minio server /data/minio --console-address ":8900"'
volumes:
  minio:
    driver: local